
services:
  app:
    build: .
    image: henriquetec:latest
    container_name: app
    hostname: app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=henrique
      - DB_PASSWORD=senha_segura
      - DB_NAME=henrique
      - ADMIN_PASSWORD=admin
      - ENABLE_RECAPTCHA=True
      - RECAPTCHA_SITE_KEY=fake_recaptcha_site_key_jkl012
      - RECAPTCHA_SECRET_KEY=fake_recaptcha_secret_mno345
    restart: unless-stopped

  db:
    image: mysql:latest
    container_name: db
    hostname: db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: senha_de_root
      MYSQL_DATABASE: henrique
      MYSQL_USER: henrique
      MYSQL_PASSWORD: senha_segura
    ports:
      - "3306:3306"
    volumes:
      - /srv/app/db:/var/lib/mysql